// generated by stringer -type Reason; DO NOT EDIT

package exchange

import "fmt"

const _Reason_name = "R_OKR_NONER_NOT_TRADINGR_PROHIBITEDR_RESTRICTEDR_PRICE_LOWR_PRICE_HIGHR_UNACCEPTABLE"

var _Reason_index = [...]uint8{0, 4, 10, 23, 35, 47, 58, 70, 84}

func (i Reason) String() string {
	if i+1 >= Reason(len(_Reason_index)) {
		return fmt.Sprintf("Reason(%d)", i)
	}
	return _Reason_name[_Reason_index[i]:_Reason_index[i+1]]
}
