// generated by stringer -type Status,Mode,Action,SumLen,TradeStatus; DO NOT EDIT

package exchange

import "fmt"

const _Status_name = "S_OPENS_CLOSES_PAUSES_RESUMES_QUOTA_REACHED"

var _Status_index = [...]uint8{0, 6, 13, 20, 28, 43}

func (i Status) String() string {
	if i+1 >= Status(len(_Status_index)) {
		return fmt.Sprintf("Status(%d)", i)
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}

const _Mode_name = "M_AUCTIONM_DEALERM_BOTH"

var _Mode_index = [...]uint8{0, 9, 17, 23}

func (i Mode) String() string {
	if i+1 >= Mode(len(_Mode_index)) {
		return fmt.Sprintf("Mode(%d)", i)
	}
	return _Mode_name[_Mode_index[i]:_Mode_index[i+1]]
}

const _Action_name = "A_NONEA_BIDA_ASK"

var _Action_index = [...]uint8{0, 6, 11, 16}

func (i Action) String() string {
	if i+1 >= Action(len(_Action_index)) {
		return fmt.Sprintf("Action(%d)", i)
	}
	return _Action_name[_Action_index[i]:_Action_index[i+1]]
}

const _SumLen_name = "SL_DAYSL_WEEKSL_CYCLE"

var _SumLen_index = [...]uint8{0, 6, 13, 21}

func (i SumLen) String() string {
	if i+1 >= SumLen(len(_SumLen_index)) {
		return fmt.Sprintf("SumLen(%d)", i)
	}
	return _SumLen_name[_SumLen_index[i]:_SumLen_index[i+1]]
}

const _TradeStatus_name = "TS_UNKNOWNTS_SUBMITTEDTS_ACKNOWLEDGEDTS_PAIDTS_RECIEVEDTS_CLOSED"

var _TradeStatus_index = [...]uint8{0, 10, 22, 37, 44, 55, 64}

func (i TradeStatus) String() string {
	if i+1 >= TradeStatus(len(_TradeStatus_index)) {
		return fmt.Sprintf("TradeStatus(%d)", i)
	}
	return _TradeStatus_name[_TradeStatus_index[i]:_TradeStatus_index[i+1]]
}
